### ISSUE TITLE
OOP

### ISSUE THREAD

**Issue by RichardRam87** [djam-jones/Mythe#1]
``` c
public void SetHealth()
    {
        //Set Enemy Health for the types of enemies
        if(typeEnemy == Enemy.basic)
        {
            maxHealth = 50;
            hasAttack = false;
        }
        else if(typeEnemy == Enemy.aerial)
        {
            maxHealth = 75;
            hasAttack = true;
        }
        else if(typeEnemy == Enemy.dive)
        {
            maxHealth = 25;
            hasAttack = true;
        }

        Debug.Log ("Health: " + maxHealth + " on Type: " + typeEnemy);
    }

```

Bestand: https://github.com/djam-jones/Mythe/blob/master/ProjectMap/Assets/Scripts/Enemies/EnemyBase.cs

Deze switch statement & functie verwaarloosd het OOP principe. De functie SetHealth() heeft voor elke class een andere implementatie. 
In de baseclass is deze functie dus virtual of abstract. Vervolgens implementeer je deze functie in de inherent-class

**Comment by 221boy221** [comment]
Dit zat na de eerste week al niet meer in ons project.
Djamali was vergeten hem te sluiten.
