### ISSUE TITLE
Andere naam

### ISSUE THREAD

**Issue by BerendWeij** [djam-jones/Mythe#10]
``` c
SaveLoadData 
```

Bestand: https://github.com/djam-jones/Mythe/blob/master/Assets/Scripts/Game/SaveLoadData.cs

Wat slaat deze Class op?
Geef de Class de naam van wat hij doet. 'save' 'load' komt al voor in de functienamen. De Classname zegt nu niet zoveel.
Is het een Sessie die hij opslaat? Noem de Class dan Session
Eventueel SavedGame?

**Comment by RVerhoef** [comment]
Dit is een voorbeeld script dat alleen wordt gebruikt voor vergelijking. Het script wordt verwijdert zodra de save & loading functionaliteiten zijn geïmplementeerd.
