### ISSUE TITLE
Benaming

### ISSUE THREAD

**Issue by BerendWeij** [djam-jones/Mythe#11]
``` c
ItemManipulation 
```

Bestand: https://github.com/djam-jones/Mythe/blob/master/Assets/Scripts/Player/ItemManipulation.cs

Wat gaat deze Class doen?
Is het niet meer een Recharger of iets dergelijks?

**Comment by RVerhoef** [comment]
De Class beheert het manipuleren van objecten, en activeert daarnaast de "Recharge" functie van de ManipulationPoint Class als de speler stopt met manipuleren. Het manipuleren van objecten kost punten die worden bijgevuld als de speler stopt met manipuleren.
