### ISSUE TITLE
Harde afhankelijkheid Joystick

### ISSUE THREAD

**Issue by BerendWeij** [djam-jones/Mythe#12]
``` c

        x = joystick.GetOffsetX(); 
```

Bestand: https://github.com/djam-jones/Mythe/blob/master/Assets/Scripts/Player/PlayerMovement.cs

Dit is logica de verkeerde kant op.
Nu is de speler hard afhankelijk van de joystick. Wat nou als je op een andere manier de speler wilt laten bewegen?
Nu ga je van speler -> joystick
Terwijl het meer zou moeten zijn:
joystick update() -> speler.Move
Zo ben je veel vrijer.
Je zou zelfs een extra Class er tussen kunnen zetten die luistert naar de Joystick of er iets gebeurd en die reageert vervolgens. Door een functie bij de speler aan te roepen. Zo zijn je speler en joystick goed herbruikbaar en losgekoppeld.

**Comment by 221boy221** [comment]
Ik heb het nu zo dat de joystick de value stuurt naar de PlayerTools en via daar connect ik met de player, de PlayerTools gebruikt ik nu zegmaar als tussen stap zodat geen ander script een component hoeft te accessen van de player(s).
