### ISSUE TITLE
Folder structuur

### ISSUE THREAD

**Issue by RichardRam87** [djam-jones/Mythe#13]
``` c

Prefabs     
Scripts     
_Scenes     
prefabs 
```

Bestand: https://github.com/djam-jones/Mythe/tree/master/Assets/Prefabs

Let op je folder structuur. Je hebt nu twee prefabs folders...

**Comment by 221boy221** [comment]
Dit is een bug in Git, wij drieën hebben maar 1 folder en dat is de Prefabs met de hoofdletter.
Zelfs bij een verse clone komt de 'prefabs' folder niet te voorschijn.
