### ISSUE TITLE
Tagmanagement

### ISSUE THREAD

**Issue by RichardRam87** [djam-jones/Mythe#14]
``` c
private string _humanTag = "Human"; 
```

Bestand: https://github.com/djam-jones/Mythe/blob/master/Assets/Scripts/Enemies/Guards/GuardAI.cs

Ik zou tag strings in een Tags script bijhouden. Dit maakt je tags en het het script meer herbruikbaar. Zo hoeft niet elke class die van de tag hoeft te weten hier een variabele voor te hebben.

**Comment by djam-jones** [comment]
Ik heb een Tags Script aangemaakt die alle tags van de game bevat.
