### ISSUE TITLE
OOP

### ISSUE THREAD

**Issue by RichardRam87** [djam-jones/Mythe#15]
``` c
AcidTrap.cs     
AcidTrap.cs.meta        
LaserTrap.cs        
LaserTrap.cs.meta       
Trapdoor.cs     
Trapdoor.cs.meta        
Turret.cs       
Turret.cs.meta 
```

Bestand: https://github.com/djam-jones/Mythe/tree/master/Assets/Scripts/Enemies/Traps

In je traps mis ik wat OOP structuur. Aangezien deze in de basis hetzelfde principe hebben, maar een andere uitvoering.

**Comment by djam-jones** [comment]
Al deze Traps doen allemaal iets anders en inheritten niet van een Base Trap script.
