### ISSUE TITLE
benamingen

### ISSUE THREAD

**Issue by BerendWeij** [djam-jones/Mythe#20]
``` c
//Set the Guards State to Attack.
            states = GuardStates.attacking; 
```

Bestand: https://github.com/djam-jones/Mythe/blob/master/Assets/Scripts/Enemies/Guards/GuardAI.cs

Hoe kan je dit duidelijker maken?
Je zet hier de state...
Terwijl je ook een SetState() functie hebt. Zou die functie anders moeten heten?

**Comment by djam-jones** [comment]
Dit script wordt niet meer gebruikt. We hebben de guard eruit gegooid.
