### ISSUE TITLE
Vermijd de naam 'script'

### ISSUE THREAD

**Issue by BerendWeij** [djam-jones/Mythe#21]
``` c
AllTagsScript 
```

Bestand: https://github.com/djam-jones/Mythe/blob/master/Assets/Scripts/Game/AllTagsScript.cs

Ik zou dit bestand TagConstants noemen
Of Tags.
En je variabele namen hoeven niet het woord Tag te bevatten aangezien je ze oproept met: TagConstants.player

Dit maakt wel duidelijk dat het om een tag gaat.

**Comment by djam-jones** [comment]
Veranderd in alle scripts.
