### ISSUE TITLE
Naming conventions private public

### ISSUE THREAD

**Issue by BerendWeij** [djam-jones/Mythe#22]
``` c
private float alpha = 1f;
    private int fadeDir = -1;

    private bool _humanIn;
    private bool _alienIn; 
```

Bestand: https://github.com/djam-jones/Mythe/blob/master/Assets/Scripts/Game/ChangeLevelFade.cs

Wees constant in je benamingen. Ik zie privates met een underscore en privates zonder een underscore. Kies één van de manieren om dit te schrijven en voer dit overal door.

**Comment by djam-jones** [comment]
Ik heb het veranderd. Dit was een foutje.
