### ISSUE TITLE
Verantwoordelijkheden van een Class

### ISSUE THREAD

**Issue by BerendWeij** [djam-jones/Mythe#23]
``` c
ChangeLevelFade 
```

Bestand: https://github.com/djam-jones/Mythe/blob/master/Assets/Scripts/Game/ChangeLevelFade.cs

Deze Class veronderstelt een fade te doen als je verandert van level.
Dat doet hij ook wel, maar hij gaat eerst zelf checken of dat wel mag. Ook doet hij wat dingen met de highscore.
Stel dat ik in jullie team zou komen werken, hoe weet ik dan dat ik hier moet zijn voor bijvoorbeeld: playerData.highscore = playerDate.score?

Ik verwacht dat deze Class alleen een fade doet.

Doordat je teveel doet in deze Class kan je deze Class ook niet hergebruiken in andere projecten. Hoe zou je dit kunnen aanpassen?

**Comment by djam-jones** [comment]
Ik heb de naam veranderd.
