### ISSUE TITLE
Opruimen

### ISSUE THREAD

**Issue by RichardRam87** [djam-jones/Mythe#3]
``` c
public class WaveSystem : MonoBehaviour {



} 
```

Bestand: https://github.com/djam-jones/Mythe/blob/master/ProjectMap/Assets/Scripts/Game/WaveSystem.cs

Laat lege, oude Classes en/of functies niet staan maar verwijder ze uit je repos als je ze niet meer gaat gebruiken.
Mocht je deze nog gaan gebruiken, geef dan met comments aan wat deze class gaat doen etc.

**Comment by 221boy221** [comment]
Dit zat na de eerste week al niet meer in ons project.
Djamali was vergeten hem te sluiten.
