### ISSUE TITLE
GIT repos structuur

### ISSUE THREAD

**Issue by BerendWeij** [djam-jones/Mythe#4]
``` c
ProjectMap  Added ItemManipulationScript, worked on CamLerpScript   Feb 16, 2015
.gitignore  Added Gitignore & Project   Feb 5, 2015
SaveStructure.jpg   SaveStructure 
```

Bestand: http://github.com/djam-jones/Mythe

Zorg ervoor dat je repository direct de hoofdmap bevat. Dit is netter. Nu moet je eerst 1 folder aanklikken om je project te kunnen bekijken. Dit is minder netjes richting stagebedrijven.

**Comment by 221boy221** [comment]
Thanks, moved it.
