### ISSUE TITLE
Korte beschrijving in readme

### ISSUE THREAD

**Issue by BerendWeij** [djam-jones/Mythe#5]
``` c
ProjectMap  Added ItemManipulationScript, worked on CamLerpScript   Feb 16, 2015
.gitignore  Added Gitignore & Project   Feb 5, 2015
SaveStructure.jpg   SaveStructure 
```

Bestand: http://github.com/djam-jones/Mythe

Zorg dat er een korte beschrijving van je project (wat is het? Voor welk platform? Met wie?) in je GITHub repository ReadMe staat. Als een stagebedrijf door je GITHub account heengaat dan is het gelijk een stuk duidelijker naar welke repository ze kijken.

**Comment by 221boy221** [comment]
Done ;)
